# Configurazione Marketing e Affiliazioni
babbel_affiliate_link: " <a rel="sponsored" href="https://www.awin1.com/awclick.php?gid=322314&mid=9659&awinaffid=2764918&linkid=2038224&clickref=""

# URL Immagini Banner (Sostituisci con i link reali del tuo network)
banner_top_url: "https://Nausica-c.it/assets/images/babbel-728x90-top.jpg"
banner_bottom_url: "https://Nausica-c.it/assets/images/babbel-728x90-bottom.jpg"
banner_sidebar_url: "https://Nausica-c.it/assets/images/babbel-300x250-side.jpg"

# Impostazioni SEO e Social
pinterest_url: "https://it.pinterest.com/Nausicac"
